/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

package problems

import (
	"fmt"
	"math"
	"time"
)

func isTriangular(value int) bool {
	x := float64(value)
	n := (math.Sqrt(8*x+1) - 1.0) / 2.0

	return n == math.Floor(n)
}

func isPentagonal(value int) bool {
	x := float64(value)
	n := (math.Sqrt(24*x+1) + 1.0) / 6.0

	return n == math.Floor(n)
}

type Problem45 struct{}

func (p *Problem45) Solve() (answer string, runTime time.Duration) {
	t0 := time.Now()

	i := 144
	for true {
		h := i * (2*i - 1)
		if isTriangular(h) && isPentagonal(h) {
			answer = fmt.Sprint(h)
			break
		}
		i += 1
	}

	t1 := time.Now()

	runTime = t1.Sub(t0)

	return
}
