/*
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
//
// Triangle	 	    Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
// Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
// Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.
//
// Find the next triangle number that is also pentagonal and hexagonal.
*/

package problems

import (
	"fmt"
	"github.com/dazfuller/euler/eulermath"
	"time"
)

type Problem45 struct{}

func (p *Problem45) Solve() (answer string, runTime time.Duration) {
	t0 := time.Now()

	i := 144
	for true {
		// Get the hexagonal number
		h := i * (2*i - 1)

		// Check to see if the value is also triangular and pentagonal
		if eulermath.IsTriangular(h) && eulermath.IsPentagonal(h) {
			answer = fmt.Sprint(h)
			break
		}
		i += 1
	}

	t1 := time.Now()

	runTime = t1.Sub(t0)

	return
}
